
obj-y := list.o queue.o tasks.o timers.o stream_buffer.o event_groups.o
obj-y += portable/MemMang/
#obj-y += portable/GCC/ARM_CM4_MPU/
obj-y += portable/GCC/ARM_CM4F/

ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Config
ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Config/ARMCM
ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Include
ccflags-y += -Irtos/freertos/Source/include
ccflags-y += -Irtos/freertos/Source/portable/GCC/ARM_CM4F


