// Copyright 2018 Google LLC.
// Libgsound version: 5a34367
#ifndef GSOUND_TARGET_H
#define GSOUND_TARGET_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * This header file was generated by Google GSound Services,
 * it should not be altered in any way. Please treat this as
 * a read-only file.
 *
 * This is a global GSound Target layer helper file.
 * This is the only file which Target layer implementation
 * source file needs to include to gain access to all GSound
 * Resources.
 */

#include "gsound.h"
#include "gsound_target_actions.h"
#include "gsound_target_audio.h"
#include "gsound_target_battery.h"
#include "gsound_target_ble.h"
#include "gsound_target_bt.h"
#include "gsound_target_device_actions.h"
#include "gsound_target_hotword_external.h"
#include "gsound_target_hotword_internal.h"
#include "gsound_target_info.h"
#include "gsound_target_ohd.h"
#include "gsound_target_os.h"
#include "gsound_target_ota.h"
#include "gsound_target_reset.h"
#include "gsound_target_trace.h"
#include "gsound_target_tws.h"

#ifdef __cplusplus
}
#endif

#endif  // GSOUND_TARGET_H
