// Copyright 2018 Google LLC.
// Libgsound version: 5a34367
#ifndef GSOUND_TARGET_TRACE_H
#define GSOUND_TARGET_TRACE_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/**
 * This header file was generated by Google GSound Services,
 * it should not be altered in any way. Please treat this as
 * a read-only file.
 *
 * Each function listed below must
 * be implemented for each specific
 * platform / SDK
 *
 */
#include "gsound.h"












/**
 * Perform any initialization required for the
 * tracing and assert API declared in this file
 */
void GSoundTargetTraceInit(void);

/**
 * Trace API called from GSound service.
 *
 * The filename, lineno, fmt, and
 * variable arguments must
 * be logged and/or transmitted over a UART
 * port for debugging purposes.
 *
 * Note: The parameters const char *fmt, ... together are defined
 * the same as the C printf function.
 */




void GSoundTargetTrace(const char *filename, int lineno,
                       const char *fmt, ...);


/**
 * Assert API called from GSound service.
 *
 * The filename, lineno, and condition
 * must be logged and/or communicated when
 * this function is called.
 *
 * Note: when this function is called, an Assert has
 * already failed. The condition parameter is a string
 * not a boolean.
 *
 */
void GSoundTargetTraceAssert(const char *filename,
                             int lineno, const char *condition);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif  // GSOUND_TARGET_TRACE_H
