obj-y += mpu_wrappers.o

ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Config
ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Config/ARMCM
ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Include
ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Include1
ccflags-y += -Irtos/freertos/Source/include
ccflags-y += -Irtos/freertos/Source/portable/GCC/ARM_CM4_MPU
