
obj-y += cmsis_os2.o cmsis_os1.o freertos_evr.o os_systick.o rt_MemBox.o

ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Config
ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Config/ARMCM
ccflags-y += -Irtos/freertos/CMSIS/RTOS2/FreeRTOS/Include
ccflags-y += -Irtos/freertos/Source/include
ccflags-y += -Irtos/freertos/Source/portable/GCC/ARM_CM4F
